---
- hosts: localhost
  pre_tasks:
    # To prevent unexpected problems, define the minimum Cumulus Linux
    # Release supported by this demo.
    - name: Verify Minimum Software Version
      assert:
        that: "{{ ansible_lsb.release is version_compare('3.4', '>=') }}"
        msg: >
          "You appear to be running an older workbench.
          Please delete your current workbench by adding '/delete' to your
          workbench URL and request a new one."

  tasks:
    - name: Check if the demo is already cloned
      stat:
        path: /home/cumulus/cldemo-netq/l3-clos
        get_attributes: no
        get_checksum: no
        get_md5: no
      register: clos

    - name: Clone Demo
      command: git clone -b l3-clos https://github.com/jubetz/cldemo-l3clos /home/cumulus/cldemo-netq/l3-clos 
      when: clos.stat.isdir is not defined

    - name: Create Ansible Directory
      file:
        path: /etc/ansible
        state: directory
      become: yes

    - name: Copy ansible.cfg
      copy:
        src: ansible.cfg
        dest: /etc/ansible/ansible.cfg
      become: yes

    - name: Copy Ansible hosts
      copy:
        src: hosts
        dest: /etc/ansible/hosts
      become: yes
      
  handlers:
    - name: apply networking
      command: ifreload -a
      become: yes


- hosts: network
  become: yes
  tasks:
    - name: Check if management VRF is enabled
      command: ip vrf identify
      register: vrf

    - name: Enable management VRF
      command: "{{ item }}"
      with_items:
        - net add vrf mgmt
        - net commit
      async: 1
      poll: 0
      when: vrf.stdout != "mgmt"
      register: mgmtVRF

    - name: Management VRF enabled, wait to reconnect
      wait_for_connection:
        timeout: 30
        delay: 5
      when: mgmtVRF.changed
    
- hosts: servers
  become: yes
  tasks:

    - name: Install LLDP
      apt:
        name: lldpd
        state: present
        update_cache: no
      register: installLLDP
        
    - name: Install traceroute
      apt:
        name: traceroute
        state: present
        update_cache: no
      register: installTraceroute
     
    - name: Install NTP
      apt:
        name: ntp
        update_cache: no
      register: installNTP

    - name: Enable NTP
      service:
        name: ntp
        enabled: yes
        state: started
      when: installNTP.changed

    - name: Restart Rsyslog
      service:
        name: rsyslog
        state: restarted

    - name: Fix CITC for bonds
      blockinfile:
        path: /etc/rc.local
        block: |
          /sbin/ethtool -s eth1 speed 1000 duplex full
          /sbin/ethtool -s eth2 speed 1000 duplex full
          systemctl restart networking

- hosts: network
  become: yes
  tasks:

    - name: Move Netqd.service to management VRF
      command: " {{ item }}"
      with_items:
        - systemctl stop netqd.service
        - systemctl disable netqd.service
        - systemctl enable netqd@mgmt.service
        - systemctl start netqd@mgmt.service
      when: agents.rc != 0

    - name: Locate where NTP is running
      shell: ip vrf identify $(ps -u ntp | grep -v PID | awk '{print $1}')
      register: ntp_location

    - name: Move NTP to Mgmt VRF
      command: " {{ item }} "
      with_items:
        - systemctl stop ntp.service
        - systemctl disable ntp.service
        - systemctl start ntp@mgmt.service
        - systemctl enable ntp@mgmt.service
      when: ntp_location.stdout != "mgmt"

